# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:

  test-python-template: &test-template

    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install -e '.[dev]'

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            pipenv run pytest -vvv ./tests --cov=pyql --cov-report=term-missing
          environment:
            PYTHONPATH: .

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-python-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8

  test-python-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-python-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test-python-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5


workflows:
  version: 2
  python_tests:
    jobs:
      - 'test-python-3.8'
      - 'test-python-3.7'
      - 'test-python-3.6'
      - 'test-python-3.5'
